services:
  postgres:
    env_file: ./.env
    image: postgres:14-alpine
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - ~/apps/postgres/db:/var/lib/postgresql/db
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_NAME=$DB_NAME
    expose:
      - '5432'
